<template>
  <div class="progress-page page-stack">
    <section class="page-intro"><div><span class="section-kicker">学习复盘</span><h2>看执行，也看分数是否真的在涨</h2><p>阶段进度、每日任务和测试结果会共同修正预计达标时间。</p></div><el-button type="primary" plain @click="router.push('/plan')">回到学习路线</el-button></section>
    <section class="progress-hero"><div><span>总体任务进度</span><strong>{{ store.overallProgress }}%</strong><p>当前处于第 {{ store.currentStage }} 阶段：{{ currentStage?.name }}</p></div><el-progress :percentage="store.overallProgress" :stroke-width="14" :show-text="false"/><dl><div><dt>已完成任务</dt><dd>{{ completedTasks }}/{{ store.tasks.length }}</dd></div><div><dt>当前预估分</dt><dd>{{ store.currentScore }}</dd></div><div><dt>目标分</dt><dd>{{ store.targetScore }}</dd></div><div><dt>预计达标</dt><dd>{{ store.estimatedWeeks }} 周</dd></div></dl></section>
    <section class="progress-grid">
      <el-card shadow="never" class="progress-card"><template #header><div class="card-heading"><h3>分科基础</h3><span>诊断基线</span></div></template><div class="subject-bars"><div v-for="subject in subjects" :key="subject"><div><strong>{{ subject }}</strong><span>{{ store.diagnostic.subjectScores[subject] || 0 }} / 150</span></div><el-progress :percentage="Math.round((store.diagnostic.subjectScores[subject]||0)/150*100)" :stroke-width="9" :show-text="false"/></div></div></el-card>
      <el-card shadow="never" class="progress-card"><template #header><div class="card-heading"><h3>阶段测试记录</h3><span>{{ store.stageTests.length }} 次</span></div></template><div v-if="store.stageTests.length" class="test-list"><div v-for="test in store.stageTests" :key="`${test.stage}-${test.date}`"><span>阶段 {{ test.stage }}</span><strong>{{ test.accuracy ?? Math.round(test.score / 450 * 100) }}% 正确率</strong><el-tag :type="test.passed?'success':'warning'" size="small">{{ test.passed?'达标':'建议复习' }}</el-tag><small>{{ test.date }}</small></div></div><el-empty v-else description="完成阶段测试后，这里会形成成绩轨迹" :image-size="72"/></el-card>
    </section>
  </div>
</template>
<script setup>
import { computed } from 'vue';import { useRouter } from 'vue-router';import { useApplicationStore } from '../stores/application';const router=useRouter();const store=useApplicationStore();const completedTasks=computed(()=>store.tasks.filter(item=>item.done).length);const currentStage=computed(()=>store.stages.find(item=>item.id===store.currentStage));const subjects=computed(()=>store.selectedMajor?.subjects||[])
</script>
<style scoped>
.page-stack{display:flex;flex-direction:column;gap:18px}.page-intro{display:flex;align-items:flex-start;justify-content:space-between}.page-intro h2{color:var(--ink);font-size:1.7rem}.page-intro p{margin-top:5px;color:var(--text-secondary)}.section-kicker{display:block;margin-bottom:5px;color:var(--primary);font-size:.72rem;font-weight:800;letter-spacing:.1em}.progress-hero{display:grid;grid-template-columns:190px 1fr;gap:24px;padding:28px;border:1px solid #d8e3f2;border-radius:22px;background:linear-gradient(145deg,#fff,#f2f7ff)}.progress-hero>div span{color:var(--text-muted);font-size:.75rem}.progress-hero>div strong{display:block;color:var(--ink);font-size:2.8rem;line-height:1.1}.progress-hero>div p{color:var(--text-secondary);font-size:.76rem}.progress-hero>.el-progress{align-self:center}.progress-hero dl{grid-column:1/-1;display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.progress-hero dl div{padding:13px;border-radius:12px;background:#fff}.progress-hero dt{color:var(--text-muted);font-size:.68rem}.progress-hero dd{color:var(--ink);font-size:1rem;font-weight:800}.progress-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.progress-card{border-radius:20px;border-color:var(--line)}.card-heading{display:flex;align-items:center;justify-content:space-between}.card-heading h3{color:var(--ink);font-size:1rem}.card-heading span{color:var(--text-muted);font-size:.72rem}.subject-bars{display:flex;flex-direction:column;gap:18px}.subject-bars>div>div{display:flex;justify-content:space-between;margin-bottom:7px}.subject-bars strong{color:var(--ink);font-size:.8rem}.subject-bars span{color:var(--text-muted);font-size:.72rem}.test-list{display:flex;flex-direction:column;gap:10px}.test-list>div{display:grid;grid-template-columns:1fr auto auto auto;align-items:center;gap:10px;padding:12px;border-radius:12px;background:#f6f8fc}.test-list span,.test-list small{color:var(--text-muted);font-size:.72rem}.test-list strong{color:var(--ink);font-size:.82rem}
@media(max-width:800px){.progress-grid{grid-template-columns:1fr}.progress-hero{grid-template-columns:1fr}.progress-hero dl{grid-template-columns:repeat(2,1fr)}}
</style>
