"""add institutions and admission_scores

Revision ID: f212276bc330
Revises: 02f71b29375b
Create Date: 2026-06-27 00:15:06.954855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f212276bc330'
down_revision: Union[str, Sequence[str], None] = '02f71b29375b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('duration', sa.String(length=32), nullable=True),
    sa.Column('tuition', sa.Integer(), nullable=True),
    sa.Column('teaching_site', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_id', 'code', name='uq_institution_province_code')
    )
    op.create_index(op.f('ix_institutions_code'), 'institutions', ['code'], unique=False)
    op.create_index(op.f('ix_institutions_province_id'), 'institutions', ['province_id'], unique=False)
    op.create_table('admission_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category_code', sa.String(length=16), nullable=True),
    sa.Column('category_name', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('line_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admission_scores_institution_id'), 'admission_scores', ['institution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admission_scores_institution_id'), table_name='admission_scores')
    op.drop_table('admission_scores')
    op.drop_index(op.f('ix_institutions_province_id'), table_name='institutions')
    op.drop_index(op.f('ix_institutions_code'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
